name: Publish

# Controls when the action will run.
on:
  # Triggers the workflow on push for the main branch
  push:
    branches: [master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: eu-central-1
  AWS_DISTRIBUTION_ID: ${{ secrets.AWS_DISTRIBUTION_ID }}
  AWS_BUCKET_NAME: ${{ secrets.AWS_BUCKET_NAME }}
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup node.js
        uses: actions/setup-node@v1
        with:
          node-version: 18.12.1

      - name: Build website
        run: npm install gatsby-cli && npm run clean &&npm run build

      - name: Sync long-term cacheable assets to S3
        run: |
          aws s3 sync ./public/ s3://$AWS_BUCKET_NAME \
            --exclude "*.html" \
            --exclude "*.js" \
            --exclude "page-data/*" \
            --exclude "rss.xml" \
            --exclude "sitemap*.xml" \
            --exclude "robots.txt" \
            --acl public-read \
            --delete \
            --cache-control "public, max-age=604800"

      - name: Sync hashed JavaScript files to S3
        run: |
          aws s3 sync ./public/ s3://$AWS_BUCKET_NAME \
            --include "*-*.js" \
            --include "*.js.map" \
            --include "*.css" \
            --acl public-read \
            --delete \
            --cache-control "public, max-age=604800"

      - name: Sync dynamic content to S3
        run: |
          aws s3 sync ./public/ s3://$AWS_BUCKET_NAME \
            --include "rss.xml" \
            --include "sitemap*.xml" \
            --include "robots.txt" \
            --include "page-data/*" \
            --include "*.js" \
            --exclude "*-*.js" \
            --exclude "*.js.map" \
            --acl public-read \
            --delete \
            --cache-control "public, max-age=60, must-revalidate"

      - name: Sync HTML files to S3
        run: |
          aws s3 sync ./public/ s3://$AWS_BUCKET_NAME \
            --include "*.html" \
            --acl public-read \
            --delete \
            --cache-control "public, max-age=60, must-revalidate"

      - name: Notify CloudFront about the changes
        run: aws cloudfront create-invalidation --distribution-id ${AWS_DISTRIBUTION_ID} --paths "/*"
